version: '3'

services:
  server:
    build: ./
    container_name: backend
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/diplom
      spring.jpa.hibernate.ddl-auto: create-drop
      spring.datasource.username=postgres
      spring.datasource.password=test
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"


